import Navbar from "@/components/organisms/Navbar";
import "./globals.css";
import { Rammetto_One, Kumbh_Sans } from "next/font/google";

const rammettoOne = Rammetto_One({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-rammetto",
});

const kumbhSans = Kumbh_Sans({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-kumbh-sans",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${rammettoOne.variable} ${kumbhSans.variable}, antialiased h-dvh flex flex-col w-screen overflow-hidden`}
            >
                <div className="flex w-full flex-col flex-1 bg-[url('/assets/banner-img/dot-pattern.webp')] bg-contain">
                    <Navbar />
                    <main className="flex w-full h-[calc(100%-56px)] flex-col">
                        <div
                            className="flex h-full
                         w-full flex-1 flex-col overflow-y-auto scrollbar-hide"
                        >
                            {children}
                        </div>
                    </main>
                </div>
            </body>
        </html>
    );
}
