import Navbar from "@/components/organisms/Navbar";
import { Kumbh_Sans, Rammetto_One } from "next/font/google";
import "./globals.css";

const rammettoOne = Rammetto_One({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-rammetto",
});

const kumbhSans = Kumbh_Sans({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-kumbh-sans",
    display: "swap"
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${rammettoOne.variable} ${kumbhSans.variable}, antialiased h-dvh flex flex-col w-screen overflow-hidden`}
            >
                <div className="flex w-full flex-col flex-1 h-full bg-[url('/assets/banner-img/dot-pattern.webp')] bg-cover md:bg-contain">
                    <Navbar />
                    <main className="flex w-full h-[calc(100%-56px)] flex-col overflow-y-auto scrollbar-hide">
                        <div className="flex h-fit w-full flex-col">
                            {children}
                        </div>
                    </main>
                </div>
            </body>
        </html>
    );
}
